package com.sunil.sixtcarandroid.db.model;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "CAR".
 */
@Entity
public class Car {

    @Id
    private Long id;

    @NotNull
    private String car_id;
    private String modelIdentifier;
    private String modelName;
    private String name;
    private String make;
    private String group;
    private String series;
    private String color;
    private String fuelType;
    private Double fuelLevel;
    private String transmission;
    private String licensePlate;
    private Double latitude;
    private Double longitude;
    private String innerCleanliness;
    private String carImageUrl;

    @Generated(hash = 625572433)
    public Car() {
    }

    public Car(Long id) {
        this.id = id;
    }

    @Generated(hash = 11118317)
    public Car(Long id, @NotNull String car_id, String modelIdentifier, String modelName, String name, String make, String group, String series, String color, String fuelType, Double fuelLevel, String transmission, String licensePlate, Double latitude, Double longitude, String innerCleanliness,
            String carImageUrl) {
        this.id = id;
        this.car_id = car_id;
        this.modelIdentifier = modelIdentifier;
        this.modelName = modelName;
        this.name = name;
        this.make = make;
        this.group = group;
        this.series = series;
        this.color = color;
        this.fuelType = fuelType;
        this.fuelLevel = fuelLevel;
        this.transmission = transmission;
        this.licensePlate = licensePlate;
        this.latitude = latitude;
        this.longitude = longitude;
        this.innerCleanliness = innerCleanliness;
        this.carImageUrl = carImageUrl;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getCar_id() {
        return car_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCar_id(@NotNull String car_id) {
        this.car_id = car_id;
    }

    public String getModelIdentifier() {
        return modelIdentifier;
    }

    public void setModelIdentifier(String modelIdentifier) {
        this.modelIdentifier = modelIdentifier;
    }

    public String getModelName() {
        return modelName;
    }

    public void setModelName(String modelName) {
        this.modelName = modelName;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getMake() {
        return make;
    }

    public void setMake(String make) {
        this.make = make;
    }

    public String getGroup() {
        return group;
    }

    public void setGroup(String group) {
        this.group = group;
    }

    public String getSeries() {
        return series;
    }

    public void setSeries(String series) {
        this.series = series;
    }

    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public String getFuelType() {
        return fuelType;
    }

    public void setFuelType(String fuelType) {
        this.fuelType = fuelType;
    }

    public Double getFuelLevel() {
        return fuelLevel;
    }

    public void setFuelLevel(Double fuelLevel) {
        this.fuelLevel = fuelLevel;
    }

    public String getTransmission() {
        return transmission;
    }

    public void setTransmission(String transmission) {
        this.transmission = transmission;
    }

    public String getLicensePlate() {
        return licensePlate;
    }

    public void setLicensePlate(String licensePlate) {
        this.licensePlate = licensePlate;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public String getInnerCleanliness() {
        return innerCleanliness;
    }

    public void setInnerCleanliness(String innerCleanliness) {
        this.innerCleanliness = innerCleanliness;
    }

    public String getCarImageUrl() {
        return carImageUrl;
    }

    public void setCarImageUrl(String carImageUrl) {
        this.carImageUrl = carImageUrl;
    }

}
