package com.sunil.sixtcarandroid.db.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sunil.sixtcarandroid.db.model.Car;

import com.sunil.sixtcarandroid.db.model.CarDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig carDaoConfig;

    private final CarDao carDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        carDaoConfig = daoConfigMap.get(CarDao.class).clone();
        carDaoConfig.initIdentityScope(type);

        carDao = new CarDao(carDaoConfig, this);

        registerDao(Car.class, carDao);
    }
    
    public void clear() {
        carDaoConfig.clearIdentityScope();
    }

    public CarDao getCarDao() {
        return carDao;
    }

}
